<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="TestSuite" duration-ms="47" started-at="2019-11-19T19:47:01Z" finished-at="2019-11-19T19:47:01Z">
    <groups>
    </groups>
    <test name="mergeSortTest" duration-ms="47" started-at="2019-11-19T19:47:01Z" finished-at="2019-11-19T19:47:01Z">
      <class name="practiceTests.SpaceEditionTests">
        <test-method status="PASS" signature="findDuplicate_Test4()[pri:0, instance:practiceTests.SpaceEditionTests@2f7a2457]" name="findDuplicate_Test4" duration-ms="17" started-at="2019-11-19T11:47:01Z" finished-at="2019-11-19T11:47:01Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[ Invalid Integer in the Array, Should be less than7!!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException:  Invalid Integer in the Array, Should be less than7!!
	at practiseProblems.SpaceEdition.findDuplicates(SpaceEdition.java:13)
	at practiceTests.SpaceEditionTests.findDuplicate_Test4(SpaceEditionTests.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findDuplicate_Test4 -->
        <test-method status="FAIL" signature="findDuplicate_Test3()[pri:0, instance:practiceTests.SpaceEditionTests@2f7a2457]" name="findDuplicate_Test3" duration-ms="17" started-at="2019-11-19T11:47:01Z" finished-at="2019-11-19T11:47:01Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[ Invalid Integer in the Array, Should be less than7!!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException:  Invalid Integer in the Array, Should be less than7!!
	at practiseProblems.SpaceEdition.findDuplicates(SpaceEdition.java:13)
	at practiceTests.SpaceEditionTests.findDuplicate_Test3(SpaceEditionTests.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findDuplicate_Test3 -->
      </class> <!-- practiceTests.SpaceEditionTests -->
    </test> <!-- mergeSortTest -->
  </suite> <!-- TestSuite -->
</testng-results>
