<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="3" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="98" started-at="2019-12-20T20:41:54Z" finished-at="2019-12-20T20:41:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="98" started-at="2019-12-20T20:41:54Z" finished-at="2019-12-20T20:41:54Z">
      <class name="practiceTests.FibSeriesTests">
        <test-method status="PASS" signature="fibSeries_Test1()[pri:0, instance:practiceTests.FibSeriesTests@6767c1fc]" name="fibSeries_Test1" duration-ms="26" started-at="2019-12-20T20:41:54Z" finished-at="2019-12-20T20:41:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fibSeries_Test1 -->
        <test-method status="PASS" signature="fibSeries_Test2()[pri:0, instance:practiceTests.FibSeriesTests@6767c1fc]" name="fibSeries_Test2" duration-ms="5" started-at="2019-12-20T20:41:54Z" finished-at="2019-12-20T20:41:54Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Should be greater than Zero!!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Should be greater than Zero!!
at practiseProblems.FibinocciNumber.fib(FibinocciNumber.java:9)
at practiceTests.FibSeriesTests.fibSeries_Test2(FibSeriesTests.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fibSeries_Test2 -->
        <test-method status="PASS" signature="fibSeries_Test3()[pri:0, instance:practiceTests.FibSeriesTests@6767c1fc]" name="fibSeries_Test3" duration-ms="2" started-at="2019-12-20T20:41:54Z" finished-at="2019-12-20T20:41:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fibSeries_Test3 -->
      </class> <!-- practiceTests.FibSeriesTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
